/**
 * generated by Enhanced EcoreGen
 */
package edu.fleet;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;
import org.eclipse.emf.common.util.BasicEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Company</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.fleet.Company#getName <em>Name</em>}</li>
 *   <li>{@link edu.fleet.Company#getEmployees <em>Employees</em>}</li>
 *   <li>{@link edu.fleet.Company#getVehicles <em>Vehicles</em>}</li>
 * </ul>
 *
 * @see edu.fleet.FleetPackage#getCompany()
 * @model kind="class"
 * @generated
 */
public class Company extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getEmployees() <em>Employees</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEmployees()
   * @generated
   * @ordered
   */
  protected EList<Employee> employees;

  /**
   * The cached value of the '{@link #getVehicles() <em>Vehicles</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVehicles()
   * @generated
   * @ordered
   */
  protected EList<Vehicle> vehicles;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Company()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FleetPackage.Literals.COMPANY;
  }

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see edu.fleet.FleetPackage#getCompany_Name()
   * @model
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * Sets the value of the '{@link edu.fleet.Company#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newName the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FleetPackage.COMPANY__NAME, oldName, name));
  }

  /**
   * Returns the value of the '<em><b>Employees</b></em>' containment reference list.
   * The list contents are of type {@link edu.fleet.Employee}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Employees</em>' containment reference list.
   * @see edu.fleet.FleetPackage#getCompany_Employees()
   * @model containment="true"
   * @generated
   */
  public EList<Employee> getEmployees()
  {
    if (employees == null)
    {
      employees = new EObjectContainmentEList<Employee>(Employee.class, this, FleetPackage.COMPANY__EMPLOYEES);
    }
    return employees;
  }

  /**
   * Returns the value of the '<em><b>Vehicles</b></em>' containment reference list.
   * The list contents are of type {@link edu.fleet.Vehicle}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vehicles</em>' containment reference list.
   * @see edu.fleet.FleetPackage#getCompany_Vehicles()
   * @model containment="true"
   * @generated
   */
  public EList<Vehicle> getVehicles()
  {
    if (vehicles == null)
    {
      vehicles = new EObjectContainmentEList<Vehicle>(Vehicle.class, this, FleetPackage.COMPANY__VEHICLES);
    }
    return vehicles;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Count the number of full-time employees in a company.
   * Algorithm: Iterate through the list of employees in the company and count the number of employees with type FULL_TIME.
   * Related Features: employees
   * Related Classes: Employee, EmployeeType
   * Input: None
   * Output: The number of full-time employees in the company (int).
   * Pre-condition: The company object is initialized and the employees list is not null.
   * Post-condition: The count of full-time employees is returned.
   * <!-- end-model-doc -->
   * @model kind="operation"
   *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public int getFullTimeEmployeeCount()
  {
    int count = 0;
    for (Employee employee : getEmployees()) {
      if (employee.getType() == EmployeeType.FULL_TIME) {
        count++;
      }
    }
    return count;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Count the number of rented vehicles in a company.
   * Algorithm: Iterate through the list of vehicles in the company and count the number of vehicles that are instances of RentedVehicle.
   * Related Features: vehicles
   * Related Classes: Vehicle, RentedVehicle
   * Input: None
   * Output: The number of rented vehicles in the company (int).
   * Pre-condition: The company object is initialized and the vehicles list is not null.
   * Post-condition: The count of rented vehicles is returned.
   * <!-- end-model-doc -->
   * @model kind="operation"
   *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public int getRentedVehicleCount()
  {
    int count = 0;
    for (Vehicle vehicle : getVehicles()) {
      if (vehicle instanceof RentedVehicle) {
        count++;
      }
    }
    return count;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Find the registration numbers of all vehicles driven by part-time employees in a company.
   * Algorithm: Iterate through the list of employees in the company, filter those with type PART_TIME and have a driven vehicle, then extract the registration number of the driven vehicle.
   * Related Features: employees, vehicles
   * Related Classes: Employee, Vehicle, EmployeeType
   * Input: None
   * Output: A list of registration numbers of vehicles driven by part-time employees (List<String>). If no such vehicles, return an empty list.
   * Pre-condition: The company object is initialized and the employees list is not null.
   * Post-condition: A list of registration numbers is returned.
   * <!-- end-model-doc -->
   * @model kind="operation"
   *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<String> getPartTimeDriverVehicleRegistrationNumbers()
  {
    EList<String> registrationNumbers = new BasicEList<String>();
    for (Employee employee : getEmployees()) {
      if (employee.getType() == EmployeeType.PART_TIME && employee.getDrivenVehicle() != null) {
        registrationNumbers.add(employee.getDrivenVehicle().getRegistrationNumber());
      }
    }
    return registrationNumbers;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Find the names of all employees who are currently driving a vehicle in a company.
   * Algorithm: Iterate through the list of vehicles in the company, filter those with a current driver, then extract the name of the current driver.
   * Related Features: vehicles
   * Related Classes: Vehicle, Employee
   * Input: None
   * Output: A list of names of employees who are currently driving a vehicle (List<String>). If no such employees, return an empty list.
   * Pre-condition: The company object is initialized and the vehicles list is not null.
   * Post-condition: A list of names is returned.
   * <!-- end-model-doc -->
   * @model kind="operation"
   *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<String> getCurrentDriversNames()
  {
    EList<String> driverNames = new BasicEList<String>();
    for (Vehicle vehicle : getVehicles()) {
      if (vehicle.getCurrentDriver() != null) {
        driverNames.add(vehicle.getCurrentDriver().getName());
      }
    }
    return driverNames;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FleetPackage.COMPANY__EMPLOYEES:
        return ((InternalEList<?>)getEmployees()).basicRemove(otherEnd, msgs);
      case FleetPackage.COMPANY__VEHICLES:
        return ((InternalEList<?>)getVehicles()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FleetPackage.COMPANY__NAME:
        return getName();
      case FleetPackage.COMPANY__EMPLOYEES:
        return getEmployees();
      case FleetPackage.COMPANY__VEHICLES:
        return getVehicles();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FleetPackage.COMPANY__NAME:
        setName((String)newValue);
        return;
      case FleetPackage.COMPANY__EMPLOYEES:
        getEmployees().clear();
        getEmployees().addAll((Collection<? extends Employee>)newValue);
        return;
      case FleetPackage.COMPANY__VEHICLES:
        getVehicles().clear();
        getVehicles().addAll((Collection<? extends Vehicle>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FleetPackage.COMPANY__NAME:
        setName(NAME_EDEFAULT);
        return;
      case FleetPackage.COMPANY__EMPLOYEES:
        getEmployees().clear();
        return;
      case FleetPackage.COMPANY__VEHICLES:
        getVehicles().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FleetPackage.COMPANY__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case FleetPackage.COMPANY__EMPLOYEES:
        return employees != null && !employees.isEmpty();
      case FleetPackage.COMPANY__VEHICLES:
        return vehicles != null && !vehicles.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} // Company
