/**
 * generated by Enhanced EcoreGen
 */
package edu.fleet;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Employee</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.fleet.Employee#getName <em>Name</em>}</li>
 *   <li>{@link edu.fleet.Employee#getType <em>Type</em>}</li>
 *   <li>{@link edu.fleet.Employee#getDrivenVehicle <em>Driven Vehicle</em>}</li>
 * </ul>
 *
 * @see edu.fleet.FleetPackage#getEmployee()
 * @model kind="class"
 * @generated
 */
public class Employee extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final EmployeeType TYPE_EDEFAULT = EmployeeType.PART_TIME;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected EmployeeType type = TYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getDrivenVehicle() <em>Driven Vehicle</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDrivenVehicle()
   * @generated
   * @ordered
   */
  protected Vehicle drivenVehicle;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Employee()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FleetPackage.Literals.EMPLOYEE;
  }

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see edu.fleet.FleetPackage#getEmployee_Name()
   * @model
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * Sets the value of the '{@link edu.fleet.Employee#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newName the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FleetPackage.EMPLOYEE__NAME, oldName, name));
  }

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link edu.fleet.EmployeeType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see edu.fleet.EmployeeType
   * @see #setType(EmployeeType)
   * @see edu.fleet.FleetPackage#getEmployee_Type()
   * @model
   * @generated
   */
  public EmployeeType getType()
  {
    return type;
  }

  /**
   * Sets the value of the '{@link edu.fleet.Employee#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newType the new value of the '<em>Type</em>' attribute.
   * @see edu.fleet.EmployeeType
   * @see #getType()
   * @generated
   */
  public void setType(EmployeeType newType)
  {
    EmployeeType oldType = type;
    type = newType == null ? TYPE_EDEFAULT : newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FleetPackage.EMPLOYEE__TYPE, oldType, type));
  }

  /**
   * Returns the value of the '<em><b>Driven Vehicle</b></em>' reference.
   * It is bidirectional and its opposite is '{@link edu.fleet.Vehicle#getCurrentDriver <em>Current Driver</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Driven Vehicle</em>' reference.
   * @see #setDrivenVehicle(Vehicle)
   * @see edu.fleet.FleetPackage#getEmployee_DrivenVehicle()
   * @see edu.fleet.Vehicle#getCurrentDriver
   * @model opposite="currentDriver"
   * @generated
   */
  public Vehicle getDrivenVehicle()
  {
    if (drivenVehicle != null && drivenVehicle.eIsProxy())
    {
      InternalEObject oldDrivenVehicle = drivenVehicle;
      drivenVehicle = (Vehicle)eResolveProxy(oldDrivenVehicle);
      if (drivenVehicle != oldDrivenVehicle)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, FleetPackage.EMPLOYEE__DRIVEN_VEHICLE, oldDrivenVehicle, drivenVehicle));
      }
    }
    return drivenVehicle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Vehicle basicGetDrivenVehicle()
  {
    return drivenVehicle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDrivenVehicle(Vehicle newDrivenVehicle, NotificationChain msgs)
  {
    Vehicle oldDrivenVehicle = drivenVehicle;
    drivenVehicle = newDrivenVehicle;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FleetPackage.EMPLOYEE__DRIVEN_VEHICLE, oldDrivenVehicle, newDrivenVehicle);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * Sets the value of the '{@link edu.fleet.Employee#getDrivenVehicle <em>Driven Vehicle</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newDrivenVehicle the new value of the '<em>Driven Vehicle</em>' reference.
   * @see #getDrivenVehicle()
   * @generated
   */
  public void setDrivenVehicle(Vehicle newDrivenVehicle)
  {
    if (newDrivenVehicle != drivenVehicle)
    {
      NotificationChain msgs = null;
      if (drivenVehicle != null)
        msgs = drivenVehicle.eInverseRemove(this, FleetPackage.VEHICLE__CURRENT_DRIVER, Vehicle.class, msgs);
      if (newDrivenVehicle != null)
        msgs = newDrivenVehicle.eInverseAdd(this, FleetPackage.VEHICLE__CURRENT_DRIVER, Vehicle.class, msgs);
      msgs = basicSetDrivenVehicle(newDrivenVehicle, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FleetPackage.EMPLOYEE__DRIVEN_VEHICLE, newDrivenVehicle, newDrivenVehicle));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseAdd(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FleetPackage.EMPLOYEE__DRIVEN_VEHICLE:
        if (drivenVehicle != null)
          msgs = drivenVehicle.eInverseRemove(this, FleetPackage.VEHICLE__CURRENT_DRIVER, Vehicle.class, msgs);
        return basicSetDrivenVehicle((Vehicle)otherEnd, msgs);
    }
    return super.eInverseAdd(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FleetPackage.EMPLOYEE__DRIVEN_VEHICLE:
        return basicSetDrivenVehicle(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FleetPackage.EMPLOYEE__NAME:
        return getName();
      case FleetPackage.EMPLOYEE__TYPE:
        return getType();
      case FleetPackage.EMPLOYEE__DRIVEN_VEHICLE:
        if (resolve) return getDrivenVehicle();
        return basicGetDrivenVehicle();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FleetPackage.EMPLOYEE__NAME:
        setName((String)newValue);
        return;
      case FleetPackage.EMPLOYEE__TYPE:
        setType((EmployeeType)newValue);
        return;
      case FleetPackage.EMPLOYEE__DRIVEN_VEHICLE:
        setDrivenVehicle((Vehicle)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FleetPackage.EMPLOYEE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case FleetPackage.EMPLOYEE__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case FleetPackage.EMPLOYEE__DRIVEN_VEHICLE:
        setDrivenVehicle((Vehicle)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FleetPackage.EMPLOYEE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case FleetPackage.EMPLOYEE__TYPE:
        return type != TYPE_EDEFAULT;
      case FleetPackage.EMPLOYEE__DRIVEN_VEHICLE:
        return drivenVehicle != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", type: ");
    result.append(type);
    result.append(')');
    return result.toString();
  }

} // Employee
