/**
 * generated by Enhanced EcoreGen
 */
package edu.fleet;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see edu.fleet.FleetFactory
 * @model kind="package"
 *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen requirement='Online Food Delivery System (OFDS) is used by many companies for delivering food at the doorstep. Each company has a name. In addition, companies hire employees for food delivery. The type of an employee can be a part-time employees or a full-time employees. Each employee has a name. The system also allows the company to manage multiple vehicles. Each vehicle has a registration number. Also, the type of a vehicle can be an owned vehicle or a rented vehicle. An employee may be asigned to a vehicle as a driver for food delivery.\nFunctional requirement\uff1a\n+ Count the number of full - time employees in a company.\n\n+ Find the registration numbers of all vehicles driven by part - time employees in a company. Return empty list if no vehicles.\n\n+ Count the number of rented vehicles in a company.\n\n+ Find the names of all employees who are currently driving a vehicle in a company. Return empty list if no employee driving a vehicle.'"
 * @generated
 */
public class FleetPackage extends EPackageImpl
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final String eNAME = "fleet";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final String eNS_URI = "http://www.example.org/fleet";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final String eNS_PREFIX = "fleet";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final FleetPackage eINSTANCE = edu.fleet.FleetPackage.init();

  /**
   * The meta object id for the '{@link edu.fleet.Vehicle <em>Vehicle</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.fleet.Vehicle
   * @see edu.fleet.FleetPackage#getVehicle()
   * @generated
   */
  public static final int VEHICLE = 0;

  /**
   * The feature id for the '<em><b>Registration Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int VEHICLE__REGISTRATION_NUMBER = 0;

  /**
   * The feature id for the '<em><b>Current Driver</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int VEHICLE__CURRENT_DRIVER = 1;

  /**
   * The number of structural features of the '<em>Vehicle</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int VEHICLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.fleet.Employee <em>Employee</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.fleet.Employee
   * @see edu.fleet.FleetPackage#getEmployee()
   * @generated
   */
  public static final int EMPLOYEE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int EMPLOYEE__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int EMPLOYEE__TYPE = 1;

  /**
   * The feature id for the '<em><b>Driven Vehicle</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int EMPLOYEE__DRIVEN_VEHICLE = 2;

  /**
   * The number of structural features of the '<em>Employee</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int EMPLOYEE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link edu.fleet.Company <em>Company</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.fleet.Company
   * @see edu.fleet.FleetPackage#getCompany()
   * @generated
   */
  public static final int COMPANY = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int COMPANY__NAME = 0;

  /**
   * The feature id for the '<em><b>Employees</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int COMPANY__EMPLOYEES = 1;

  /**
   * The feature id for the '<em><b>Vehicles</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int COMPANY__VEHICLES = 2;

  /**
   * The number of structural features of the '<em>Company</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int COMPANY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link edu.fleet.OwnedVehicle <em>Owned Vehicle</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.fleet.OwnedVehicle
   * @see edu.fleet.FleetPackage#getOwnedVehicle()
   * @generated
   */
  public static final int OWNED_VEHICLE = 3;

  /**
   * The feature id for the '<em><b>Registration Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int OWNED_VEHICLE__REGISTRATION_NUMBER = VEHICLE__REGISTRATION_NUMBER;

  /**
   * The feature id for the '<em><b>Current Driver</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int OWNED_VEHICLE__CURRENT_DRIVER = VEHICLE__CURRENT_DRIVER;

  /**
   * The number of structural features of the '<em>Owned Vehicle</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int OWNED_VEHICLE_FEATURE_COUNT = VEHICLE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.fleet.RentedVehicle <em>Rented Vehicle</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.fleet.RentedVehicle
   * @see edu.fleet.FleetPackage#getRentedVehicle()
   * @generated
   */
  public static final int RENTED_VEHICLE = 4;

  /**
   * The feature id for the '<em><b>Registration Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int RENTED_VEHICLE__REGISTRATION_NUMBER = VEHICLE__REGISTRATION_NUMBER;

  /**
   * The feature id for the '<em><b>Current Driver</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int RENTED_VEHICLE__CURRENT_DRIVER = VEHICLE__CURRENT_DRIVER;

  /**
   * The number of structural features of the '<em>Rented Vehicle</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int RENTED_VEHICLE_FEATURE_COUNT = VEHICLE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.fleet.EmployeeType <em>Employee Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.fleet.EmployeeType
   * @see edu.fleet.FleetPackage#getEmployeeType()
   * @generated
   */
  public static final int EMPLOYEE_TYPE = 5;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass vehicleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass employeeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass companyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ownedVehicleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass rentedVehicleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum employeeTypeEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see edu.fleet.FleetPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private FleetPackage()
  {
    super(eNS_URI, FleetFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link FleetPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static FleetPackage init()
  {
    if (isInited) return (FleetPackage)EPackage.Registry.INSTANCE.getEPackage(FleetPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredFleetPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    FleetPackage theFleetPackage = registeredFleetPackage instanceof FleetPackage ? (FleetPackage)registeredFleetPackage : new FleetPackage();

    isInited = true;

    // Create package meta-data objects
    theFleetPackage.createPackageContents();

    // Initialize created meta-data
    theFleetPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theFleetPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(FleetPackage.eNS_URI, theFleetPackage);
    return theFleetPackage;
  }


  /**
   * Returns the meta object for class '{@link edu.fleet.Vehicle <em>Vehicle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vehicle</em>'.
   * @see edu.fleet.Vehicle
   * @generated
   */
  public EClass getVehicle()
  {
    return vehicleEClass;
  }

  /**
   * Returns the meta object for the attribute '{@link edu.fleet.Vehicle#getRegistrationNumber <em>Registration Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Registration Number</em>'.
   * @see edu.fleet.Vehicle#getRegistrationNumber()
   * @see #getVehicle()
   * @generated
   */
  public EAttribute getVehicle_RegistrationNumber()
  {
    return (EAttribute)vehicleEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for the reference '{@link edu.fleet.Vehicle#getCurrentDriver <em>Current Driver</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Current Driver</em>'.
   * @see edu.fleet.Vehicle#getCurrentDriver()
   * @see #getVehicle()
   * @generated
   */
  public EReference getVehicle_CurrentDriver()
  {
    return (EReference)vehicleEClass.getEStructuralFeatures().get(1);
  }

  /**
   * Returns the meta object for class '{@link edu.fleet.Employee <em>Employee</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Employee</em>'.
   * @see edu.fleet.Employee
   * @generated
   */
  public EClass getEmployee()
  {
    return employeeEClass;
  }

  /**
   * Returns the meta object for the attribute '{@link edu.fleet.Employee#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.fleet.Employee#getName()
   * @see #getEmployee()
   * @generated
   */
  public EAttribute getEmployee_Name()
  {
    return (EAttribute)employeeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.fleet.Employee#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see edu.fleet.Employee#getType()
   * @see #getEmployee()
   * @generated
   */
  public EAttribute getEmployee_Type()
  {
    return (EAttribute)employeeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * Returns the meta object for the reference '{@link edu.fleet.Employee#getDrivenVehicle <em>Driven Vehicle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Driven Vehicle</em>'.
   * @see edu.fleet.Employee#getDrivenVehicle()
   * @see #getEmployee()
   * @generated
   */
  public EReference getEmployee_DrivenVehicle()
  {
    return (EReference)employeeEClass.getEStructuralFeatures().get(2);
  }

  /**
   * Returns the meta object for class '{@link edu.fleet.Company <em>Company</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Company</em>'.
   * @see edu.fleet.Company
   * @generated
   */
  public EClass getCompany()
  {
    return companyEClass;
  }

  /**
   * Returns the meta object for the attribute '{@link edu.fleet.Company#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.fleet.Company#getName()
   * @see #getCompany()
   * @generated
   */
  public EAttribute getCompany_Name()
  {
    return (EAttribute)companyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for the containment reference list '{@link edu.fleet.Company#getEmployees <em>Employees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Employees</em>'.
   * @see edu.fleet.Company#getEmployees()
   * @see #getCompany()
   * @generated
   */
  public EReference getCompany_Employees()
  {
    return (EReference)companyEClass.getEStructuralFeatures().get(1);
  }

  /**
   * Returns the meta object for the containment reference list '{@link edu.fleet.Company#getVehicles <em>Vehicles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vehicles</em>'.
   * @see edu.fleet.Company#getVehicles()
   * @see #getCompany()
   * @generated
   */
  public EReference getCompany_Vehicles()
  {
    return (EReference)companyEClass.getEStructuralFeatures().get(2);
  }

  /**
   * Returns the meta object for class '{@link edu.fleet.OwnedVehicle <em>Owned Vehicle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Owned Vehicle</em>'.
   * @see edu.fleet.OwnedVehicle
   * @generated
   */
  public EClass getOwnedVehicle()
  {
    return ownedVehicleEClass;
  }

  /**
   * Returns the meta object for class '{@link edu.fleet.RentedVehicle <em>Rented Vehicle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rented Vehicle</em>'.
   * @see edu.fleet.RentedVehicle
   * @generated
   */
  public EClass getRentedVehicle()
  {
    return rentedVehicleEClass;
  }

  /**
   * Returns the meta object for enum '{@link edu.fleet.EmployeeType <em>Employee Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Employee Type</em>'.
   * @see edu.fleet.EmployeeType
   * @generated
   */
  public EEnum getEmployeeType()
  {
    return employeeTypeEEnum;
  }

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  public FleetFactory getFleetFactory()
  {
    return (FleetFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    vehicleEClass = createEClass(VEHICLE);
    createEAttribute(vehicleEClass, VEHICLE__REGISTRATION_NUMBER);
    createEReference(vehicleEClass, VEHICLE__CURRENT_DRIVER);

    employeeEClass = createEClass(EMPLOYEE);
    createEAttribute(employeeEClass, EMPLOYEE__NAME);
    createEAttribute(employeeEClass, EMPLOYEE__TYPE);
    createEReference(employeeEClass, EMPLOYEE__DRIVEN_VEHICLE);

    companyEClass = createEClass(COMPANY);
    createEAttribute(companyEClass, COMPANY__NAME);
    createEReference(companyEClass, COMPANY__EMPLOYEES);
    createEReference(companyEClass, COMPANY__VEHICLES);

    ownedVehicleEClass = createEClass(OWNED_VEHICLE);

    rentedVehicleEClass = createEClass(RENTED_VEHICLE);

    // Create enums
    employeeTypeEEnum = createEEnum(EMPLOYEE_TYPE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    ownedVehicleEClass.getESuperTypes().add(this.getVehicle());
    rentedVehicleEClass.getESuperTypes().add(this.getVehicle());

    // Initialize classes and features; add operations and parameters
    initEClass(vehicleEClass, Vehicle.class, "Vehicle", IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getVehicle_RegistrationNumber(), ecorePackage.getEString(), "registrationNumber", null, 0, 1, Vehicle.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getVehicle_CurrentDriver(), this.getEmployee(), this.getEmployee_DrivenVehicle(), "currentDriver", null, 0, 1, Vehicle.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(employeeEClass, Employee.class, "Employee", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEmployee_Name(), ecorePackage.getEString(), "name", null, 0, 1, Employee.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEmployee_Type(), this.getEmployeeType(), "type", null, 0, 1, Employee.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEmployee_DrivenVehicle(), this.getVehicle(), this.getVehicle_CurrentDriver(), "drivenVehicle", null, 0, 1, Employee.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(companyEClass, Company.class, "Company", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCompany_Name(), ecorePackage.getEString(), "name", null, 0, 1, Company.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCompany_Employees(), this.getEmployee(), null, "employees", null, 0, -1, Company.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCompany_Vehicles(), this.getVehicle(), null, "vehicles", null, 0, -1, Company.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    addEOperation(companyEClass, ecorePackage.getEInt(), "getFullTimeEmployeeCount", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(companyEClass, ecorePackage.getEInt(), "getRentedVehicleCount", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(companyEClass, ecorePackage.getEString(), "getPartTimeDriverVehicleRegistrationNumbers", 0, -1, IS_UNIQUE, IS_ORDERED);

    addEOperation(companyEClass, ecorePackage.getEString(), "getCurrentDriversNames", 0, -1, IS_UNIQUE, IS_ORDERED);

    initEClass(ownedVehicleEClass, OwnedVehicle.class, "OwnedVehicle", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(rentedVehicleEClass, RentedVehicle.class, "RentedVehicle", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    // Initialize enums and add enum literals
    initEEnum(employeeTypeEEnum, EmployeeType.class, "EmployeeType");
    addEEnumLiteral(employeeTypeEEnum, EmployeeType.PART_TIME);
    addEEnumLiteral(employeeTypeEEnum, EmployeeType.FULL_TIME);

    // Create resource
    createResource(eNS_URI);

    // Create annotations
    // http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen
    createEnhancedCodeGenAnnotations();
  }

  /**
   * Initializes the annotations for <b>http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen</b>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected void createEnhancedCodeGenAnnotations()
  {
    String source = "http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen";
    addAnnotation
      (this,
       source,
       new String[]
       {
         "requirement", "Online Food Delivery System (OFDS) is used by many companies for delivering food at the doorstep. Each company has a name. In addition, companies hire employees for food delivery. The type of an employee can be a part-time employees or a full-time employees. Each employee has a name. The system also allows the company to manage multiple vehicles. Each vehicle has a registration number. Also, the type of a vehicle can be an owned vehicle or a rented vehicle. An employee may be asigned to a vehicle as a driver for food delivery.\nFunctional requirement\uff1a\n+ Count the number of full - time employees in a company.\n\n+ Find the registration numbers of all vehicles driven by part - time employees in a company. Return empty list if no vehicles.\n\n+ Count the number of rented vehicles in a company.\n\n+ Find the names of all employees who are currently driving a vehicle in a company. Return empty list if no employee driving a vehicle."
       });
    addAnnotation
      (companyEClass.getEOperations().get(0),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (companyEClass.getEOperations().get(1),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (companyEClass.getEOperations().get(2),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (companyEClass.getEOperations().get(3),
       source,
       new String[]
       {
         "generated", "true"
       });
  }

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  public interface Literals
  {
    /**
     * The meta object literal for the '{@link edu.fleet.Vehicle <em>Vehicle</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.fleet.Vehicle
     * @see edu.fleet.FleetPackage#getVehicle()
     * @generated
     */
    public static final EClass VEHICLE = eINSTANCE.getVehicle();

    /**
     * The meta object literal for the '<em><b>Registration Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute VEHICLE__REGISTRATION_NUMBER = eINSTANCE.getVehicle_RegistrationNumber();

    /**
     * The meta object literal for the '<em><b>Current Driver</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference VEHICLE__CURRENT_DRIVER = eINSTANCE.getVehicle_CurrentDriver();

    /**
     * The meta object literal for the '{@link edu.fleet.Employee <em>Employee</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.fleet.Employee
     * @see edu.fleet.FleetPackage#getEmployee()
     * @generated
     */
    public static final EClass EMPLOYEE = eINSTANCE.getEmployee();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute EMPLOYEE__NAME = eINSTANCE.getEmployee_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute EMPLOYEE__TYPE = eINSTANCE.getEmployee_Type();

    /**
     * The meta object literal for the '<em><b>Driven Vehicle</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference EMPLOYEE__DRIVEN_VEHICLE = eINSTANCE.getEmployee_DrivenVehicle();

    /**
     * The meta object literal for the '{@link edu.fleet.Company <em>Company</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.fleet.Company
     * @see edu.fleet.FleetPackage#getCompany()
     * @generated
     */
    public static final EClass COMPANY = eINSTANCE.getCompany();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute COMPANY__NAME = eINSTANCE.getCompany_Name();

    /**
     * The meta object literal for the '<em><b>Employees</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference COMPANY__EMPLOYEES = eINSTANCE.getCompany_Employees();

    /**
     * The meta object literal for the '<em><b>Vehicles</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference COMPANY__VEHICLES = eINSTANCE.getCompany_Vehicles();

    /**
     * The meta object literal for the '{@link edu.fleet.OwnedVehicle <em>Owned Vehicle</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.fleet.OwnedVehicle
     * @see edu.fleet.FleetPackage#getOwnedVehicle()
     * @generated
     */
    public static final EClass OWNED_VEHICLE = eINSTANCE.getOwnedVehicle();

    /**
     * The meta object literal for the '{@link edu.fleet.RentedVehicle <em>Rented Vehicle</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.fleet.RentedVehicle
     * @see edu.fleet.FleetPackage#getRentedVehicle()
     * @generated
     */
    public static final EClass RENTED_VEHICLE = eINSTANCE.getRentedVehicle();

    /**
     * The meta object literal for the '{@link edu.fleet.EmployeeType <em>Employee Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.fleet.EmployeeType
     * @see edu.fleet.FleetPackage#getEmployeeType()
     * @generated
     */
    public static final EEnum EMPLOYEE_TYPE = eINSTANCE.getEmployeeType();

  }

} //FleetPackage
