/**
 * generated by Enhanced EcoreGen
 */
package edu.fleet;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Owned Vehicle</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.fleet.FleetPackage#getOwnedVehicle()
 * @model kind="class"
 * @generated
 */
public class OwnedVehicle extends Vehicle
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OwnedVehicle()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FleetPackage.Literals.OWNED_VEHICLE;
  }

} // OwnedVehicle
