/**
 * generated by Enhanced EcoreGen
 */
package edu.fleet;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rented Vehicle</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.fleet.FleetPackage#getRentedVehicle()
 * @model kind="class"
 * @generated
 */
public class RentedVehicle extends Vehicle
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RentedVehicle()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FleetPackage.Literals.RENTED_VEHICLE;
  }

} // RentedVehicle
