/**
 * generated by Enhanced EcoreGen
 */
package edu.fleet;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Vehicle</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.fleet.Vehicle#getRegistrationNumber <em>Registration Number</em>}</li>
 *   <li>{@link edu.fleet.Vehicle#getCurrentDriver <em>Current Driver</em>}</li>
 * </ul>
 *
 * @see edu.fleet.FleetPackage#getVehicle()
 * @model kind="class" abstract="true"
 * @generated
 */
public abstract class Vehicle extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The default value of the '{@link #getRegistrationNumber() <em>Registration Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRegistrationNumber()
   * @generated
   * @ordered
   */
  protected static final String REGISTRATION_NUMBER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRegistrationNumber() <em>Registration Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRegistrationNumber()
   * @generated
   * @ordered
   */
  protected String registrationNumber = REGISTRATION_NUMBER_EDEFAULT;

  /**
   * The cached value of the '{@link #getCurrentDriver() <em>Current Driver</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCurrentDriver()
   * @generated
   * @ordered
   */
  protected Employee currentDriver;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Vehicle()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FleetPackage.Literals.VEHICLE;
  }

  /**
   * Returns the value of the '<em><b>Registration Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Registration Number</em>' attribute.
   * @see #setRegistrationNumber(String)
   * @see edu.fleet.FleetPackage#getVehicle_RegistrationNumber()
   * @model
   * @generated
   */
  public String getRegistrationNumber()
  {
    return registrationNumber;
  }

  /**
   * Sets the value of the '{@link edu.fleet.Vehicle#getRegistrationNumber <em>Registration Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newRegistrationNumber the new value of the '<em>Registration Number</em>' attribute.
   * @see #getRegistrationNumber()
   * @generated
   */
  public void setRegistrationNumber(String newRegistrationNumber)
  {
    String oldRegistrationNumber = registrationNumber;
    registrationNumber = newRegistrationNumber;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FleetPackage.VEHICLE__REGISTRATION_NUMBER, oldRegistrationNumber, registrationNumber));
  }

  /**
   * Returns the value of the '<em><b>Current Driver</b></em>' reference.
   * It is bidirectional and its opposite is '{@link edu.fleet.Employee#getDrivenVehicle <em>Driven Vehicle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Current Driver</em>' reference.
   * @see #setCurrentDriver(Employee)
   * @see edu.fleet.FleetPackage#getVehicle_CurrentDriver()
   * @see edu.fleet.Employee#getDrivenVehicle
   * @model opposite="drivenVehicle"
   * @generated
   */
  public Employee getCurrentDriver()
  {
    if (currentDriver != null && currentDriver.eIsProxy())
    {
      InternalEObject oldCurrentDriver = currentDriver;
      currentDriver = (Employee)eResolveProxy(oldCurrentDriver);
      if (currentDriver != oldCurrentDriver)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, FleetPackage.VEHICLE__CURRENT_DRIVER, oldCurrentDriver, currentDriver));
      }
    }
    return currentDriver;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Employee basicGetCurrentDriver()
  {
    return currentDriver;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCurrentDriver(Employee newCurrentDriver, NotificationChain msgs)
  {
    Employee oldCurrentDriver = currentDriver;
    currentDriver = newCurrentDriver;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FleetPackage.VEHICLE__CURRENT_DRIVER, oldCurrentDriver, newCurrentDriver);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * Sets the value of the '{@link edu.fleet.Vehicle#getCurrentDriver <em>Current Driver</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newCurrentDriver the new value of the '<em>Current Driver</em>' reference.
   * @see #getCurrentDriver()
   * @generated
   */
  public void setCurrentDriver(Employee newCurrentDriver)
  {
    if (newCurrentDriver != currentDriver)
    {
      NotificationChain msgs = null;
      if (currentDriver != null)
        msgs = currentDriver.eInverseRemove(this, FleetPackage.EMPLOYEE__DRIVEN_VEHICLE, Employee.class, msgs);
      if (newCurrentDriver != null)
        msgs = newCurrentDriver.eInverseAdd(this, FleetPackage.EMPLOYEE__DRIVEN_VEHICLE, Employee.class, msgs);
      msgs = basicSetCurrentDriver(newCurrentDriver, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FleetPackage.VEHICLE__CURRENT_DRIVER, newCurrentDriver, newCurrentDriver));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseAdd(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FleetPackage.VEHICLE__CURRENT_DRIVER:
        if (currentDriver != null)
          msgs = currentDriver.eInverseRemove(this, FleetPackage.EMPLOYEE__DRIVEN_VEHICLE, Employee.class, msgs);
        return basicSetCurrentDriver((Employee)otherEnd, msgs);
    }
    return super.eInverseAdd(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FleetPackage.VEHICLE__CURRENT_DRIVER:
        return basicSetCurrentDriver(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FleetPackage.VEHICLE__REGISTRATION_NUMBER:
        return getRegistrationNumber();
      case FleetPackage.VEHICLE__CURRENT_DRIVER:
        if (resolve) return getCurrentDriver();
        return basicGetCurrentDriver();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FleetPackage.VEHICLE__REGISTRATION_NUMBER:
        setRegistrationNumber((String)newValue);
        return;
      case FleetPackage.VEHICLE__CURRENT_DRIVER:
        setCurrentDriver((Employee)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FleetPackage.VEHICLE__REGISTRATION_NUMBER:
        setRegistrationNumber(REGISTRATION_NUMBER_EDEFAULT);
        return;
      case FleetPackage.VEHICLE__CURRENT_DRIVER:
        setCurrentDriver((Employee)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FleetPackage.VEHICLE__REGISTRATION_NUMBER:
        return REGISTRATION_NUMBER_EDEFAULT == null ? registrationNumber != null : !REGISTRATION_NUMBER_EDEFAULT.equals(registrationNumber);
      case FleetPackage.VEHICLE__CURRENT_DRIVER:
        return currentDriver != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (registrationNumber: ");
    result.append(registrationNumber);
    result.append(')');
    return result.toString();
  }

} // Vehicle
